"""Create messages table

Revision ID: e3b9eea1685b
Revises: 7e7662b490fa
Create Date: 2025-06-26 23:33:24.863353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b9eea1685b'
down_revision = '7e7662b490fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
